[package]
name = "wechat-multi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
iced-x86 = "1.21.0"
mach_object = "0.1.17"
